exportList: {
  html: {
    activated: false,
    outFolderPath: "doc/html",
    theme: default,
    displaySectionCode: true,
    displayRuleCode: false,
    onePageDoc: false,
    namespace: 'N/A'
  },

  dokuWiki: {
    activated: true,
    outFolderPath: 'C:\wamp64\www\apcDoc\data\pages\apc_web_service\',
    theme: default,
    displaySectionCode: true,
    displayRuleCode: false,
    onePageDoc: false,
    namespace: apc_web_service
  },

  markdown: {
    activated: false,
    outFolderPath: "doc/markdown",
    theme: default,
    displaySectionCode: true,
    displayRuleCode: false,
    onePageDoc: false,
    namespace: 'N/A'
  },

  text: {
    activated: false,
    outFolderPath: "doc/text",
    theme: default,
    displaySectionCode: true,
    displayRuleCode: false,
    onePageDoc: false,
    namespace: 'N/A'
  },

}