exportList: {
  html: {
    activated: true,
    outFolderPath: "doc/html",
    theme: default
  },

  dokuWiki: {
    activated: true,
    outFolderPath: "doc/doku",
    theme: default
  },

  markdown: {
    activated: true,
    outFolderPath: "doc/markdown",
    theme: default
  },

  text: {
    activated: true,
    outFolderPath: "doc/text",
    theme: default
  },

}